# Project information
site_name: kelsey_experiments
# defeine TOC or order of website-
nav:
  - Home: index.md
  - HLD and LLD: pipeline_block_digram.md
  - Stage Info: stage_info.md


site_author: Rajesh Thakur
site_description: >-
  This Repo is dedicated for Generating the Training pipeline

# Repository
repo_name: GetZuma/kelsey_experiments
repo_url: https://github.com/GetZuma/kelseyAI_training_deployments.git

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/GetZuma"  target="_blank" rel="noopener">Rajesh Kumar Thakur</a>